server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ $uri.html /404.html =404;
  }

  gzip on;
  gzip_types text/css application/javascript application/json image/svg+xml application/wasm;

  add_header X-Content-Type-Options nosniff;
  add_header X-Frame-Options SAMEORIGIN;
}
